import React from 'react';
import SEO from '../SEO/SEO';

const LegalLayout = ({ children, title }) => (
    <div style={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '8rem 2rem 4rem',
        background: 'var(--bg-dark)',
        color: 'var(--text-main)',
        lineHeight: '1.6'
    }}>
        <SEO
            title={`${title} - Qaint`}
            description={`${title} for Qaint, the professional and free demo recording tool.`}
        />
        <div style={{ maxWidth: '800px', width: '100%' }}>
            <h1 style={{ fontSize: '2.5rem', marginBottom: '2rem', color: 'var(--primary)' }}>{title}</h1>
            <div style={{ background: 'rgba(255,255,255,0.03)', padding: '2.5rem', borderRadius: '1.5rem', border: '1px solid rgba(255,255,255,0.05)' }}>
                {children}
            </div>
        </div>
    </div>
);

export const PrivacyPolicy = () => (
    <LegalLayout title="Privacy Policy">
        <section>
            <p>Last Updated: February 27, 2026</p>

            <p>
                Qaint is built local-first. Your recordings remain on your device unless you explicitly choose to export or upload them. We do not operate a centralized server that stores your videos.
            </p>

            <h3>Information We Process: </h3>

            <h4>Local Recording Data</h4>
            <p>
                Videos, thumbnails, and related metadata are saved directly to your device using browser-based file system access.
            </p>

            <h4>Optional Cloud Access</h4>
            <p>
                If you enable Google Drive export, we request permission to create and manage files within your Drive. We only access files generated by Qaint.
            </p>

            <h4>Authentication Data</h4>
            <p>
                If you sign in for optional features, basic profile information such as name and email may be processed solely for authentication.
            </p>

            <h3>How Data Is Used</h3>
            <p>
                Connected account information is used only to enable optional export and synchronization features.
            </p>
            <p>
                Qaint does not sell, rent, or share personal data with third parties.
            </p>

            <h3>Data Storage and Retention</h3>
            <p>
                Qaint does not maintain a centralized video storage backend. Your recordings remain on your device or in your connected cloud account.
            </p>
            <p>
                You retain full control over access, deletion, and management of your files.
            </p>

            <h3>Security</h3>
            <p>
                Authentication and cloud connections use industry-standard OAuth protocols. All external communication occurs over secure HTTPS connections.
            </p>

            <h3>Your Control</h3>
            <p>
                You may revoke cloud permissions at any time through your Google account settings. Deleting local files permanently removes them from your device.
            </p>

            <h3>No Tracking</h3>
            <p>
                Qaint does not use invasive third-party tracking scripts or behavioral advertising systems.
            </p>

            <p>
                For questions regarding this policy, contact hi@qaint.in.
            </p>
        </section>
    </LegalLayout>
);

export const TermsOfService = () => (
    <LegalLayout title="Terms of Service">
        <section>
            <p>Last Updated: February 27, 2026</p>

            <p>
                By accessing or using Qaint, you agree to these Terms of Service. If you do not agree, please discontinue use of the application.
            </p>

            <h3>Use of the Application</h3>
            <p>
                Qaint is provided as a local-first product demo recording tool. You may use it for personal or commercial purposes in accordance with applicable laws.
            </p>

            <h3>Ownership of Content</h3>
            <p>
                You retain full ownership of all recordings and content created using Qaint. We do not claim ownership over your files.
            </p>

            <h3>Acceptable Use</h3>
            <p>
                You agree not to use Qaint for unlawful activities, to violate intellectual property rights, or to record or distribute content in violation of applicable regulations.
            </p>

            <h3>No Warranty</h3>
            <p>
                Qaint is provided on an "as is" and "as available" basis without warranties of any kind, express or implied.
            </p>

            <h3>Limitation of Liability</h3>
            <p>
                Qaint Lab is not responsible for data loss resulting from local device failure, third-party service interruptions, or user error. You are responsible for maintaining backups of important recordings.
            </p>

            <h3>Changes to These Terms</h3>
            <p>
                We may update these Terms from time to time. Continued use of Qaint after updates constitutes acceptance of the revised terms.
            </p>

            <p>
                For questions regarding these Terms, contact hi@qaint.in.
            </p>
        </section>
    </LegalLayout>
);
